/**
 * Services index
 *
 * Export all services from this module
 */

export {
  DeviceDiscoveryService,
  getDeviceDiscoveryService,
  discoverDevices,
  type DiscoveredDevice,
  type DeviceDiscoveryOptions,
  type DeviceDiscoveryResult,
  type DevicePlatform,
  type DeviceType,
} from './device-discovery/index.js';

export type { AndroidDeviceDiscovery } from './device-discovery/android-discovery.js';
export type { IOSDeviceDiscovery } from './device-discovery/ios-discovery.js';

// Appium Server Service
export {
  AppiumServer,
  AppiumServerManager,
  getAppiumManager,
  resetAppiumManager,
  startAppiumServer,
  stopAppiumServer,
  stopAllAppiumServers,
  getAppiumServerInfo,
  getAllAppiumServers,
  getRunningAppiumServers,
  checkAppiumServerHealth,
  findAvailablePort,
  isPortAvailable,
  releasePort,
  releaseAllPorts,
  LogBuffer,
  LogCaptureStream,
  createLogCaptureStream,
  type AppiumServerConfig,
  type AppiumServerInfo,
  type AppiumServerStatus,
  type AppiumLogLevel,
  type HealthCheckOptions,
  type HealthCheckResult,
  type AppiumLogEntry,
  AppiumServerError,
  AppiumStartupError,
  AppiumShutdownError,
  AppiumHealthCheckError,
  PortAllocationError,
} from './appium-server/index.js';

// Driver Session Management Service
export {
  DriverSession,
  DriverSessionManager,
  getSessionManager,
  resetSessionManager,
  createDriverSession,
  createBatchDriverSessions,
  getDriverSession,
  getDriverSessionInfo,
  getAllDriverSessions,
  filterDriverSessions,
  stopDriverSession,
  deleteDriverSession,
  stopAllDriverSessions,
  deleteAllDriverSessions,
  healthCheckDriverSession,
  healthCheckAllDriverSessions,
  reconnectDriverSession,
  getDriverSessionStatistics,
  addDriverSessionEventListener,
  getActiveDriverSessionCount,
  getTotalDriverSessionCount,
  type DriverSessionConfig,
  type DriverSessionInfo,
  type DriverSessionStatus,
  type DriverPlatform,
  type AutomationName,
  type BaseDriverCapabilities,
  type SessionHealthCheckResult,
  type SessionStatistics,
  type SessionFilterOptions,
  type BatchSessionOptions,
  type BatchSessionResult,
  type SessionEvent,
  type SessionEventType,
  type SessionEventListener,
  DriverSessionError,
  SessionCreationError,
  SessionTerminationError,
  SessionConnectionError,
  SessionReconnectError,
  SessionHealthCheckError,
  SessionNotFoundError,
  SessionStateError,
  DeviceUnavailableError,
  ServerUnavailableError,
  BatchSessionError,
  InvalidCapabilitiesError,
} from './driver-session/index.js';

// Natural Language Test Parser Service
export {
  NLTestParser,
  getNLTestParser,
  resetNLTestParser,
  type TestStep,
  type TestAssertion,
  type TestDataRequirement,
  type ParsedTestCase,
  type ParserOptions,
  type ParserResult,
  type BatchParseInput,
  type BatchParseResult,
  NLTestParserError,
  ParserErrorType,
} from './nl-test-parser/index.js';

// Test Data Generator Service
export {
  TestDataGenerator,
  type DataSchema,
  type EdgeCaseType,
  type GenerationOptions,
  type GenerationResult,
  type BatchGenerationRequest,
  type BatchGenerationResult,
} from './test-data-generator/index.js';

// Notification Service
export {
  NotificationService,
  NotificationServiceError,
  getNotificationService,
  resetNotificationService,
  createNotificationService,
  type NotificationChannel,
  type NotificationDeliveryStatus,
  type NotificationTrigger,
  type NotificationSeverity,
  type NotificationRule,
  type NotificationFilter,
  type NotificationData,
  type SlackConfig,
  type EmailConfig,
  type WebhookConfig,
  type NotificationResult,
  type TestSummaryReport,
  type NotificationServiceConfig,
} from './notification/index.js';

// Element Location Service
export {
  ElementLocator,
  createElementLocator,
  SelectorParser,
  getSelectorParser,
  parseSelector,
  byId,
  byXPath,
  byAccessibilityId,
  byCss,
  byText,
  TimeoutHandler,
  createTimeoutHandler,
  FallbackStrategyManager,
  createFallbackManager,
  LocatorType,
  LocatorPriority,
  ElementLocationError,
  LocationErrorType,
  type LocatorStrategy,
  type ElementLocatorConfig,
  type LocationResult,
  type LocationAttempt,
  type LocationOptions,
  type ParsedSelector,
  type LocationDriver,
  type ElementHandle,
  type TimeoutOptions,
  type TimeoutResult,
  type FallbackConfig,
  type FallbackResult,
} from './element-location/index.js';

// Test Code Generator Service
export {
  TestCodeGenerator,
  getTestCodeGenerator,
  resetTestCodeGenerator,
  type TestFramework,
  type Language,
  type PatternStyle,
  type MobilePlatform,
  type LocatorStrategy as CodeLocatorStrategy,
  type ElementLocator as CodeElementLocator,
  type PageObject,
  type PageMethod,
  type Parameter,
  type GeneratedTestFile,
  type CodeGenerationOptions,
  type CodeGenerationResult,
  type BatchCodeGenerationInput,
  type BatchCodeGenerationResult,
  type FrameworkCapabilities,
  type CodeTemplate,
  TestCodeGeneratorError,
  CodeGenerationErrorType,
  getTemplate,
  getTemplatesForFramework,
  getTemplateKeys,
  CODE_GENERATION_SYSTEM_PROMPT,
  CODE_GENERATION_JSON_SCHEMA,
  DEFAULT_CODE_GENERATION_EXAMPLES,
  frameworkCapabilities,
} from './test-code-generator/index.js';

// Action Executor Service
export {
  ActionExecutor,
  createActionExecutor,
  WaitHandler,
  createWaitHandler,
  ScreenshotCapture,
  createScreenshotCapture,
  getActionExecutor,
  resetActionExecutor,
  executeAction,
  executeBatch,
  ActionType,
  SwipeDirection,
  ActionExecutorErrorType,
  ActionExecutorError,
  type ActionSelector,
  type Point,
  type Rect,
  type SwipeConfig,
  type TapConfig,
  type InputConfig,
  type WaitConfig,
  type ScreenshotConfig,
  type GestureStep,
  type PinchConfig,
  type MobileAction,
  type ScreenshotMetadata,
  type ActionResult,
  type BatchExecutionOptions,
  type BatchExecutionResult,
  type ActionExecutorConfig,
  type ActionDriver,
  type ElementHandle as ActionElementHandle,
} from './action-executor/index.js';

// Accessibility Testing Service
export {
  AccessibilityTester,
  createAccessibilityTester,
  getAccessibilityTester,
  resetAccessibilityTester,
  IOSA11yScanner,
  createIOSA11yScanner,
  AndroidA11yScanner,
  createAndroidA11yScanner,
  ContrastAnalyzer,
  createContrastAnalyzer,
  getContrastAnalyzer,
  resetContrastAnalyzer,
  quickScan,
  scanCriticalIssues,
  AccessibilitySeverity,
  AccessibilityViolationType,
  AccessibilityErrorType,
  AccessibilityError,
  type AccessibilityViolation,
  type ContrastResult,
  type FocusResult,
  type TouchTargetResult,
  type AccessibilityScanResult,
  type AccessibilityScanConfig,
  type AccessibilityTreeNode,
  type AccessibilityDriver,
} from './accessibility-testing/index.js';

// Coverage Explorer Service
export {
  CoverageExplorer,
  createCoverageExplorer,
  CoverageAnalyzer,
  createCoverageAnalyzer,
  ElementDiscoveryService,
  createElementDiscoveryService,
  createExplorationStrategy,
  BFSExplorationStrategy,
  DFSExplorationStrategy,
  RandomExplorationStrategy,
  SmartExplorationStrategy,
  ExplorationStrategy,
  ExplorationStatus,
  InteractionType,
  CoverageExplorerErrorType,
  CoverageExplorerError,
  type DiscoveredElement,
  type ElementDiscoveryOptions,
  type ScreenState,
  type ExplorationEdge,
  type ExplorationConfig,
  type ExplorationProgress,
  type ExplorationResult,
  type ExplorationStatistics,
  type TestCaseSuggestion,
  type CoverageGap,
  type NavigationGraph,
  type IExplorationStrategy,
} from './coverage-explorer/index.js';

// Failure Analyzer Service
export {
  FailureAnalyzer,
  getFailureAnalyzer,
  resetFailureAnalyzer,
  buildFailureAnalysisPrompt,
  FAILURE_ANALYSIS_SYSTEM_PROMPT,
  FAILURE_ANALYSIS_JSON_SCHEMA,
  FAILURE_ANALYSIS_EXAMPLES,
  FailureCategory,
  FlakinessConfidence,
  FailureSeverity,
  FailureAnalyzerErrorType,
  FailureAnalyzerError,
  type FailureContext,
  type FailureAnalysis,
  type AnalysisOptions,
  type BatchAnalysisInput,
  type BatchAnalysisResult,
  type FixAction,
  type RootCauseHypothesis,
  type FlakinessAnalysis,
} from './failure-analyzer/index.js';

// Selenium Converter Service
export {
  SeleniumConverter,
  getSeleniumConverter,
  resetSeleniumConverter,
  JavaSeleniumParser,
  createJavaParser,
  PythonSeleniumParser,
  createPythonParser,
  ConverterCodeGenerator,
  createCodeGenerator,
  convertLocator,
  getFrameworkImports,
  getTestWrapperKeywords,
  API_MAPPINGS,
  getAssertionMatcher,
  type SourceLanguage,
  type TargetFramework,
  type SeleniumActionType,
  type LocatorType,
  type ParsedLocator,
  type ParsedAction,
  type ParsedStep,
  type ParsedAssertion,
  type ParsedSeleniumTestCase,
  type ParsedSeleniumTestSuite,
  type ConversionOptions,
  type ConversionResult,
  type ConversionSummary,
  type GeneratedTestFile,
  type ApiMapping,
  type ApiMappingParameter,
  type ConverterErrorType,
  SeleniumConverterError,
} from './selenium-converter/index.js';

// Security Scanner Service
export {
  SecurityScanner,
  getSecurityScanner,
  resetSecurityScanner,
  scanSecurity,
  quickSecurityScan,
  scanForAPIKeys,
  APIKeyDetector,
  InsecureStorageChecker,
  NetworkConfigChecker,
  SecurityReportGenerator,
  SecurityCategory,
  SecuritySeverity,
  SecurityReportFormat,
  type AnySecurityFinding,
  type SecurityFinding,
  type InsecureStorageFinding,
  type ExposedAPIKeyFinding,
  type InsecureNetworkFinding,
  type SecurityScanOptions,
  type SecurityScanResult,
  type SecurityScanSummary,
  type SecurityReportOptions,
  type SecurityReport,
  type APIKeyPattern,
  type InsecureStoragePattern,
  type NetworkSecurityCheck,
} from './security-scanner/index.js';

// Maintenance Service
export {
  MaintenanceService,
  getMaintenanceService,
  resetMaintenanceService,
  startMaintenanceService,
  stopMaintenanceService,
  MaintenanceScheduler,
  getMaintenanceScheduler,
  ArtifactCleaner,
  createArtifactCleaner,
  SessionPruner,
  createSessionPruner,
  DBOptimizer,
  createDBOptimizer,
  QueueCleaner,
  createQueueCleaner,
  MaintenanceTaskStatus,
  MaintenanceTaskType,
  MaintenanceEventType,
  type MaintenanceTaskResult,
  type MaintenanceServiceConfig,
  type ArtifactCleanupConfig,
  type SessionPruningConfig,
  type DBOptimizationConfig,
  type QueueCleanupConfig,
  type MaintenanceStatistics,
  type UsagePattern,
  type MaintenanceWindowRecommendation,
  type MaintenanceEvent,
  type MaintenanceEventHandler,
} from './maintenance/index.js';

// Visual Regression Detector Service
export {
  VisualRegressionDetector,
  getGlobalVisualRegressionDetector,
  resetGlobalVisualRegressionDetector,
  createVisualRegressionDetector,
  DifferenceSeverity,
  VisualRegressionError,
  VisualRegressionErrorType,
  type VisualRegressionOptions,
  type VisualRegressionResult,
  type VisualRegressionDetectorConfig,
  type PixelComparisonResult,
  type LLMAnalysisResult,
  type VisualDifference,
  type IgnoreRegion,
} from './visual-regression-detector/index.js';

// Visual Baseline Service
export {
  VisualBaselineService,
  getGlobalVisualBaselineService,
  resetGlobalVisualBaselineService,
  createVisualBaselineService,
  type VisualBaseline,
  type VisualBaselineMetadata,
  type VisualBaselineCaptureOptions,
  type VisualBaselineComparisonOptions,
  type VisualBaselineComparisonResult,
  type VisualBaselineConfig,
  type DeviceMetadata,
  type AppVersionMetadata,
} from './visual-baseline/index.js';
